<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '266487c54d44515d7beb725741db4a96',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'DATABASE_URL' => 'LLava',
);
