<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAtczxcF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAtczxcF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAtczxcF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAtczxcF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAtczxcF\App_KernelDevDebugContainer([
    'container.build_hash' => 'AtczxcF',
    'container.build_id' => '90b02978',
    'container.build_time' => 1677765087,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAtczxcF');
